Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: "t4g.small"                 # Change to preferred instance type
      ImageId: "ami-0c8eea98010057bd0"         # AMI ID (e.g., Ubuntu 24)
      SecurityGroupIds:
        - !Ref MySecurityGroup                 # Refers to security group below
      SubnetId:                                 # Optional, can be left out for default VPC
        Fn::Select:
          - 0
          - Fn::GetAZs: ""
  MySecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Enable SSH access"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22                         # Allows SSH access on port 22
          ToPort: 22
          CidrIp: "0.0.0.0/0"                  # Note: This allows access from any IP
